org: admissionbot
app: admission-bot
service: serverless-fastapi

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, "dev"}
  environment:
    BOT_TOKEN: ${param:BOT_TOKEN}
    API_HOST: ${param:API_HOST}
    API_TOKEN: ${param:API_TOKEN}

    WEBHOOK_HOST: ${param:WEBHOOK_HOST}

package:
  exclude:
    - Makefile
    - poetry.lock
    - README.md
    - tests/**
    - docs/**
    - node_modules/**
    - .venv/**
    - .serverless/**
    - package.json
    - package-lock.json
    - .pytest_cache
    - .hypothesis

custom:
  pythonRequirements:
    fileName: requirements.lock
    slim: false
    dockerizePip: 'non-linux'
    layer:
      name: serverless-fastapi-deps
      description: Dependencies of serverless-fastapi
      compatibleRuntimes:
        - python3.11

functions:
  api:
    handler: app.main.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: any
          path: /{proxy+}