"""Added confirm edbo

Revision ID: 106ade32a9f4
Revises: 3a8794f84774
Create Date: 2023-08-04 19:08:01.356973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106ade32a9f4'
down_revision = '3a8794f84774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_users', sa.Column('confirm_edbo', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_users', 'confirm_edbo')
    # ### end Alembic commands ###
