"""Added telegram_id

Revision ID: 3a8794f84774
Revises: 1f090223d8ab
Create Date: 2023-08-03 01:34:50.713795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8794f84774'
down_revision = '1f090223d8ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_users', 'telegram_id')
    # ### end Alembic commands ###
