"""Added payment type

Revision ID: 3b013a100a40
Revises: 022e4ccc401b
Create Date: 2023-08-06 00:32:50.618839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b013a100a40'
down_revision = '022e4ccc401b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_users', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_users', 'payment_type')
    # ### end Alembic commands ###
