"""Added speciality

Revision ID: ebb2adfc3c0b
Revises: b9153e7a5a21
Create Date: 2023-08-01 23:37:40.125480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb2adfc3c0b'
down_revision = 'b9153e7a5a21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('speciality', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'speciality')
    # ### end Alembic commands ###
