"""Upgraded user

Revision ID: fda5f6ea4ffe
Revises: e555b8755ff8
Create Date: 2023-08-01 17:12:54.646125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda5f6ea4ffe'
down_revision = 'e555b8755ff8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('dorm', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('print_edbo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'print_edbo')
    op.drop_column('users', 'dorm')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
