name: Deploy master branch

on:
  push:
    branches:
      - 'dev'
      - 'main'
  workflow_dispatch:
    inputs:
      stage:
        description: Deployment stage
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install serverless
        run: |
          npm install serverless@3.x
          npx serverless plugin install --name serverless-python-requirements
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('requirements.lock') }}
      - name: Install the project dependencies
        run: uv pip install -r requirements.lock
      - name: Install Plugin and Deploy
        run: npx serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}