name: Deploy master branch

on:
  push:
    branches:
      - 'dev'
      - 'main'
  workflow_dispatch:
    inputs:
      stage:
        description: Deployment stage
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install the project dependencies
        shell: bash
        run: pip install -r requirements.lock
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-python-requirements && serverless deploy"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}